language: node_js
node_js:
    - '8'
    - '9'
    - '10'
    - 'node'
cache:
    yarn: true
    directories:
        - node_modules
install:
    - yarn install
script:
    - yarn lint
    - yarn check:src
branches:
    only:
        - master
