language: node_js
node_js:
    - '8'
    - '9'
    - '10'
    - 'node'
cache:
    directories:
        - node_modules
script:
    - npm run lint
    - npm run check:src
branches:
    only:
        - master
